FROM node:20-alpine

WORKDIR /app

ARG REACT_APP_API_URL
ARG REACT_APP_LIMIT_LIST_USER
ARG REACT_APP_LIMIT_LIST_BOOK
ENV REACT_APP_API_URL=$REACT_APP_API_URL
ENV REACT_APP_LIMIT_LIST_USER=$REACT_APP_LIMIT_LIST_USER
ENV REACT_APP_LIMIT_LIST_BOOK=$REACT_APP_LIMIT_LIST_BOOK

COPY package*.json . 
RUN npm install

COPY . .

EXPOSE 3000

CMD ["npm", "start"]
