version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: ${REACT_APP_API_URL}
        REACT_APP_LIMIT_LIST_BOOK: ${REACT_APP_LIMIT_LIST_BOOK}
        REACT_APP_LIMIT_LIST_USER: ${REACT_APP_LIMIT_LIST_USER}
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - backend

  backend:
    build:
      context: ../backend-book
      dockerfile: Dockerfile
      args:
        PORT: ${PORT}
    ports:
      - "5000:5000"
    env_file:
      - ../backend-book/.env
