version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - backend
    volumes:
      - .:/app
    environment:
      - CHOKIDAR_USEPOLLING=true # Kích hoạt hot reload trên React
    command: ["npm", "start"]

  backend:
    build:
      context: ../backend-book
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ../backend-book/.env
    volumes:
      - ../backend-book:/usr/src/app
    working_dir: /usr/src/app
    environment:
      - WATCHPACK_POLLING=true # Hỗ trợ hot reload cho Node.js
    command: ["npm", "run", "dev"]
